sudo: required
services:
  - docker

bofore_install:
  - docker build -t nnoussair/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true nnoussair/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "DockerReact"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-2-799960955376"
  bucket_path: "DockerReact"
  on:
    branch: master

  acess_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
